image: humancellatlas/dss-build-box

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GITHUB_API: "https://api.github.com"
  GIT_DEPTH: "3"

stages:
  - test
  - deploy
  - integration_test
  - promote_integration

before_script:
  - virtualenv ~/venv
  - source ~/venv/bin/activate
  - pip install -r requirements-dev.txt
  - source environment

.tests:
  stage: test
  except:
    - tags
    - schedules

security_checks:
  extends: .tests
  before_script:
      - virtualenv ~/venv
      - source ~/venv/bin/activate
  script:
    - pip install trufflehog
    - wget -O regex.json https://raw.githubusercontent.com/HumanCellAtlas/dcplib/master/components/trufflehog_regex_patterns.json
    - trufflehog --regex --rules regex.json --entropy=False https://github.com/HumanCellAtlas/fusillade.git
    - rm regex.json

unit_tests:
  extends: .tests
  script:
    - make unittest

deploy:
  stage: deploy
  script:
    - ./scripts/populate_deployment_environment.py $CI_COMMIT_REF_NAME -p > environment.local
    - make deploy
  only:
    - master
    - integration
    - staging
  except:
    - schedules

integration_test:
  stage: integration_test
  script:
    - ./scripts/populate_deployment_environment.py $CI_COMMIT_REF_NAME -p > environment.local
    - make integration_test
  only:
    - master
    - integration
    - staging
  except:
    - schedules

promote_integration:
  stage: promote_integration
  script:
    - ./scripts/promote.py integration --auto
  only:
    - master