image: humancellatlas/dss-build-box

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GITHUB_API: "https://api.github.com"
  GIT_DEPTH: "3"

stages:
  - test
  - deploy
  - integration_test
  - promote_integration
  - promote_staging
  - promote_production

before_script:
  - virtualenv ~/venv
  - source ~/venv/bin/activate
  - pip install -r requirements-dev.txt
  - source environment

.tests:
  stage: test
  except:
    - tags
    - schedules

security_checks:
  extends: .tests
  before_script:
      - virtualenv ~/venv
      - source ~/venv/bin/activate
  script:
    - pip install trufflehog
    - wget -O regex.json https://raw.githubusercontent.com/HumanCellAtlas/dcplib/master/components/trufflehog_regex_patterns.json
    - trufflehog --regex --rules regex.json --entropy=False https://github.com/HumanCellAtlas/fusillade.git
    - rm regex.json

unit_tests:
  extends: .tests
  script:
    - make unittest

deploy:
  stage: deploy
  script:
    - scripts/populate_deployment_environment.py $CI_COMMIT_REF_NAME -p > environment.local
    - make deploy
  only:
    - master
    - integration
    - staging
  except:
    - schedules

integration_test:
  stage: integration_test
  script:
    - scripts/populate_deployment_environment.py $CI_COMMIT_REF_NAME -p > environment.local
    - make integration_test
  only:
    - master
    - integration
    - staging
  except:
    - schedules

.promote_integration:
  stage: promote_integration
  except:
    - tags
    - schedules

integration_major:
  stage: promote_integration
  script:
    - scripts/promote.py integration --auto --release major
  only:
    - master
  when: manual

integration_minor:
  stage: promote_integration
  script:
    - scripts/promote.py integration --auto --release minor
  only:
    - master
  when: manual

integration_patch:
  stage: promote_integration
  script:
    - scripts/promote.py integration --auto --release patch
  only:
    - master
  when: manual

integration_build:
  stage: promote_integration
  script:
    - scripts/promote.py integration --auto --release build
  only:
    - master
  when: manual

promote_staging:
  stage: promote_staging
  except:
    - tags
    - schedules
  script:
    - scripts/promote.py staging --auto
  only:
    - integration
  when: manual

promote_production:
  stage: promote_staging
  except:
    - tags
    - schedules
  script:
    - scripts/promote.py production --auto
  only:
    - staging
  when: manual