language: python
cache: pip

python:
  - 3.6

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_DEFAULT_OUTPUT=json

before_install:
  - source environment

install:
  - pip install -r requirements-dev.txt

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
