openapi: 3.0.0
info:
  title: Fusillade Internal API Documentation
  description: |
    Human Cell Atlas Data Coordination Platform Fusillade internal APIs.
  version: $FUS_VERSION
servers:
  - url: https://$API_DOMAIN_NAME/internal
paths:
  /cb:
    get:
      summary: An internal endpoint that should not be used.
      tags:
        - oauth
      operationId: fusillade.api.oauth.cb
      responses:
        200:
          description: Returned a authorization token.
  /version:
    get:
      summary: Return the version of the deployed system
      operationId: fusillade.api.internal.version
      responses:
        200:
          description: Version returned.

  /health:
    get:
      summary: Return the health status of the deployed system
      operationId: fusillade.api.internal.health_check
      responses:
        200:
          description: Health status returned.
